name: de_radar
version: "1.0.0"
config-version: 2
profile: de_radar
model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  de_radar:
    staging:
      +materialized: view
    marts:
      +materialized: table
